# Generated by Django 5.1.7 on 2025-05-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('business_name', models.CharField(max_length=100)),
                ('business_about', models.TextField()),
                ('bio', models.TextField()),
                ('language', models.CharField(choices=[('English', 'English'), ('Pidgin', 'Pidgin'), ('French', 'French'), ('Yoruba', 'Yoruba'), ('Hausa', 'Hausa'), ('Igbo', 'Igbo'), ('Others', 'Others')], max_length=100)),
                ('service_years', models.CharField(max_length=100)),
                ('min_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('certification', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('proof_of_address', models.FileField(blank=True, null=True, upload_to='proof_of_address/')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('NIGHT', 'Night')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
