# Generated by Django 5.1.7 on 2025-05-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityoption',
            name='name',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('NIGHT', 'Night')], max_length=10, unique=True),
        ),
    ]
