# Generated by Django 5.1.7 on 2025-05-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_availabilityoption_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
