# Generated by Django 5.1.7 on 2025-05-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_artisanprofile_first_name_artisanprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='proof_of_address',
            field=models.FileField(blank=True, null=True, upload_to='proof_of_address/'),
        ),
    ]
