# Generated by Django 5.1.7 on 2025-05-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_artisanprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanprofile',
            name='service_years',
            field=models.CharField(choices=[('1', '1 year'), ('2', '2 years'), ('3', '3 years'), ('4', '4 years'), ('5', '5 years'), ('6', '6 years'), ('7', '7 years'), ('8', '8 years'), ('9', '9 years'), ('10', '10 years +')], max_length=100),
        ),
    ]
